clear
echo -e "\e[32;32m "
echo " _          _                        _      _"
echo "| |    ___ | |_ _   _ ___  ___   ___(_) ___| |_ _   _"
echo "| |   / _ \| __| | | / __|/ _ \ / __| |/ _ \ __| | | |"
echo "| |__| (_) | |_| |_| \__ \ (_) | (__| |  __/ |_| |_| |"
echo "|_____\___/ \__|\__,_|___/\___/ \___|_|\___|\__|\__, |"
echo "                                                |___/"
echo "                  ©Lotusociety Team"
echo -e "\e[32;33m       ╚═══╦═════════════════════════════╦═══╝"
echo -e "\e[32;34m ╔═════════╩═════════════════════════════╩═════════╗"
echo -e "\e[32;33m ║    Welcome to Lotusociety Screen of Lotusociety ║"
echo -e "\e[32;35m ║          Full Methods Layer 7 Bypasser          ║"
echo -e "\e[32;31m ╚╦═══════════════════════════════════════════════╦╝"
echo -e "\e[32;33m  ╚══════╦════════════════════════════════╦═══════╝"
echo -e "\e[32;34m        ╔╩════════════════════════════════╩╗"
echo -e "\e[32;33m        ║ Type [Target] To See All Commands║"
echo -e "\e[32;35m        ╚╦════════════════════════════════╦╝"
echo -e "\e[32;31m         ║ - - EXPIRATION [2/12/2022] - - ║"
echo -e "\e[32;33m ╔═══════╩════════════════════════════════╩════════╗"
echo -e "\e[32;34m ║             Full Power By Lotusociety           ║"
echo -e "\e[32;33m ║       Copyright © 2022 By Lotusociety Team      ║"
echo -e "\e[32;35m ╚═════════════════════════════════════════════════╝"
echo "...:::: DDoS Tool v2.3 - Copyright : @Lotusociety ::::...."
echo ""
java ddos.java
